services:
  backend:
    build: ./backend
    container_name: accounting-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  # Frontend service removed - Electron desktop apps should run locally
  # Use: cd frontend && npm run start:dev

networks:
  app-network:
