services:
  backend:
    build: ./backend
    container_name: accounting-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - app-network

  # Frontend service removed - Electron desktop apps should run locally
  # Use: cd frontend && npm run start:dev

  postgres:
    image: postgres:15
    container_name: accounting-postgres
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: accounting
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
