services:
  backend:
    build: ./backend
    container_name: accounting-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: accounting-desktop
    # Note: Electron apps don't need port exposure in Docker
    # They run as desktop applications
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - DISPLAY=${DISPLAY}
    volumes:
      # Mount the source code for development
      - ./frontend/src:/app/src
      # Allow access to X11 for GUI (Linux)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  postgres:
    image: postgres:15
    container_name: accounting-postgres
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: accounting
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
